
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OM SAI RAM
 */
public class DASHBOARD extends javax.swing.JFrame {
    Connection con=null;
    sig obj = new sig();
 
       
    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() throws SQLException {
        super("ADMISSION MANAGEMENT SYSTEM");
        initComponents();
         con =DriverManager.getConnection("jdbc:mysql://localhost:3306/ams","root","");
        // ab.fun();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleframe = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        titlename1 = new javax.swing.JLabel();
        titlename3 = new javax.swing.JLabel();
        titlename2 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id1 = new javax.swing.JTextField();
        L5 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox<String>();
        c10 = new javax.swing.JComboBox<String>();
        L6 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        L19 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        titlename23 = new javax.swing.JLabel();
        titlename27 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        titlename24 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        titlename25 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        titlename26 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        t4 = new javax.swing.JComboBox();
        titlename33 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        titlename28 = new javax.swing.JLabel();
        titlename29 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        titlename30 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        titlename31 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        titlename32 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        L17 = new javax.swing.JLabel();
        L18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleframe.setBackground(new java.awt.Color(0, 153, 153));
        titleframe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        titleframe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital-building-clipart-vector_csp45854550.jpg"))); // NOI18N
        logo.setText("jLabel1");
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton10.setText("Logout");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        titlename1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename1.setForeground(new java.awt.Color(255, 255, 255));
        titlename1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename1.setText("HOSPITAL MANAGEMENT SYSTEM");
        titlename1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename1.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout titleframeLayout = new javax.swing.GroupLayout(titleframe);
        titleframe.setLayout(titleframeLayout);
        titleframeLayout.setHorizontalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(777, 777, 777)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleframeLayout.createSequentialGroup()
                    .addContainerGap(458, Short.MAX_VALUE)
                    .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(438, 438, 438)))
        );
        titleframeLayout.setVerticalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titleframeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleframeLayout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );

        getContentPane().add(titleframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        titlename3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titlename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename3.setText("Basic Detail");
        titlename3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename3.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, -1));

        titlename2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename2.setText(" Patient Medicine Dashboard :");
        titlename2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename2.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 550, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Problum Cateogry:");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 20));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Patient Room Type:");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 150, 20));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Patient Room No:");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 20));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Prefer Docter Name:");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 150, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Patient Status:");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, 20));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Check in Date:");
        jLabel54.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 90, 20));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Marital Status:");
        jLabel53.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 20));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Gender:");
        jLabel52.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 90, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Name:");
        jLabel1.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 20));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Pin code:");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 80, 10));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Country:");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, 80, 20));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("State:");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 360, 60, 20));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Distric:");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 60, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Address:");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 60, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Email:");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 60, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Phone no:");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 144, 33));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 144, 33));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Close");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 144, 33));
        jPanel1.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1390, 300));

        L5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L5.setText("Problum Cateogry:");
        L5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, 20));

        L7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L7.setText("Patient Room No:");
        L7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 250, 20));

        L9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L9.setText("Patient Status:");
        L9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 260, 20));

        L4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L4.setText("Check in Date:");
        L4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        L4.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 220, 20));

        L3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L3.setText("Marital Status:");
        L3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        L3.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 20));

        L2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2.setText("Gender:");
        L2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        L2.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 240, 20));

        L1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L1.setText("Patient Name:");
        L1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L1.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 250, 20));

        L16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L16.setText("Pin code:");
        L16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 310, 20));

        L15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L15.setText("Country:");
        L15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 300, 20));

        L14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L14.setText("State:");
        L14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 320, 20));

        L13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L13.setText("Distric:");
        L13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 320, -1));

        L12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L12.setText("Address:");
        L12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 300, -1));

        c5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "10Th", "12Th", "MCA", "BCA", "BBA", "MBA", "BSC", "MSC", "BA", "B.COM", "B.TECH", "M.TECH", "M.COM", "DIPLOMA" }));
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 330, 80, -1));

        c10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------", "Adhar Card", "Voter Id", "Driving Liacence", "Pan Card", "College Id Card" }));
        getContentPane().add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 380, 80, -1));

        L6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L6.setText("Patient Room Type:");
        L6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, 20));

        L8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L8.setText("Prefer Docter Name:");
        L8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        L19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L19.setText("patient_REG");
        L19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        L10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L10.setText("Phone no:");
        L10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        L11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L11.setText("Email:");
        L11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel74.setText("patient_REG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L19, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 174, Short.MAX_VALUE)
                .addComponent(L10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L11)
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 380, 370));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        titlename23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename23.setText("Tablet name:");
        titlename23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename23.setPreferredSize(new java.awt.Dimension(450, 28));

        titlename27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename27.setText("Current  medicine status");
        titlename27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename27.setPreferredSize(new java.awt.Dimension(450, 28));

        t1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        titlename24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename24.setText("Injectionname:");
        titlename24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename24.setPreferredSize(new java.awt.Dimension(450, 28));

        t2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename25.setText("Test name :");
        titlename25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename25.setPreferredSize(new java.awt.Dimension(450, 28));

        t3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename26.setText("Stauts");
        titlename26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename26.setPreferredSize(new java.awt.Dimension(450, 28));

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", " " }));

        t4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------", "10-30% GOOD", "10-30% BAD", "10-30% MEDIUM", "40-70% GOOD", "40-70% BAD", "40-70% MEDIUM", "80-100% GOOD", "80-100% BAD", "800-100% MEDIUM", "CRITICAL", "AVERAGE", " " }));

        titlename33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename33.setText("Quantity");
        titlename33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename33.setPreferredSize(new java.awt.Dimension(450, 28));

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titlename33, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(titlename25, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titlename26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titlename23, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titlename24, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titlename27, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addComponent(t2)
                                    .addComponent(t3)
                                    .addComponent(t4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(titlename27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titlename33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titlename24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 500, 370));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        titlename28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename28.setText("Tablet name:");
        titlename28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename28.setPreferredSize(new java.awt.Dimension(450, 28));

        titlename29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename29.setText("Current  Previous status");
        titlename29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename29.setPreferredSize(new java.awt.Dimension(450, 28));

        t5.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename30.setText("Injectionname:");
        titlename30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename30.setPreferredSize(new java.awt.Dimension(450, 28));

        t6.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename31.setText("Test name :");
        titlename31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename31.setPreferredSize(new java.awt.Dimension(450, 28));

        t7.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename32.setText("Test report status :");
        titlename32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename32.setPreferredSize(new java.awt.Dimension(450, 28));

        t8.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(titlename29, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(titlename31, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(titlename32, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlename28, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlename30, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(titlename29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, -1, 370));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Pin code:");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 80, 10));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Pin code:");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 80, 10));

        L17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L17.setText("Pin code:");
        L17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 310, 20));

        L18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L18.setText("Pin code:");
        L18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 310, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        login a = null;
        try {
            a = new login();
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }

        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         t1.setText("");
      t2.setText("");
      t3.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     try {
         
       
        obj.thequery("update patient set Medicine_Name ='"+t1.getText()+"' ,Medicine_quantity ='"+c1.getSelectedItem().toString()+"' ,injection_Name ='"+t2.getText()+"' ,injection_quantity ='"+c2.getSelectedItem().toString()+"' ,testname ='"+t3.getText()+"' ,status ='"+t4.getSelectedItem().toString()+"'  where patient_id ='"+id1.getText()+"'");       
      JOptionPane.showMessageDialog(null, " thanking you go to payment section and payed the total  money  ");
      t1.setText("");
      t2.setText("");
      t3.setText("");
    
        home regFace =new home();
            regFace.setVisible(true);
            this.dispose();
      
      
    
      
     }
        catch(Exception ex){
        }
        
    }//GEN-LAST:event_jButton2MouseClicked
 
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        home regFace =new home();
        regFace.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DASHBOARD().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DASHBOARD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel L1;
    public javax.swing.JLabel L10;
    public javax.swing.JLabel L11;
    public javax.swing.JLabel L12;
    public javax.swing.JLabel L13;
    public javax.swing.JLabel L14;
    public javax.swing.JLabel L15;
    public javax.swing.JLabel L16;
    public javax.swing.JLabel L17;
    public javax.swing.JLabel L18;
    public javax.swing.JLabel L19;
    public javax.swing.JLabel L2;
    public javax.swing.JLabel L3;
    public javax.swing.JLabel L4;
    public javax.swing.JLabel L5;
    public javax.swing.JLabel L6;
    public javax.swing.JLabel L7;
    public javax.swing.JLabel L8;
    public javax.swing.JLabel L9;
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox<String> c10;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox<String> c5;
    public javax.swing.JTextField id1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JComboBox t4;
    public javax.swing.JTextField t5;
    public javax.swing.JTextField t6;
    public javax.swing.JTextField t7;
    public javax.swing.JTextField t8;
    private javax.swing.JPanel titleframe;
    private javax.swing.JLabel titlename1;
    private javax.swing.JLabel titlename2;
    private javax.swing.JLabel titlename23;
    private javax.swing.JLabel titlename24;
    private javax.swing.JLabel titlename25;
    private javax.swing.JLabel titlename26;
    private javax.swing.JLabel titlename27;
    private javax.swing.JLabel titlename28;
    private javax.swing.JLabel titlename29;
    private javax.swing.JLabel titlename3;
    private javax.swing.JLabel titlename30;
    private javax.swing.JLabel titlename31;
    private javax.swing.JLabel titlename32;
    private javax.swing.JLabel titlename33;
    // End of variables declaration//GEN-END:variables

    private void statu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
