
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OM SAI RAM
 */
public class NEWPatient extends javax.swing.JFrame {
sig obj = new sig();
Random rand = new Random(); 
  
        // Generate random integers in range 0 to 999 
        int rand_int1 = rand.nextInt(10000); 
       String numberAsString = Integer.toString(rand_int1);
    /**
     * Creates new form Patient
     */
    public NEWPatient() {
        super("ADMISSION MANAGEMENT SYSTEM");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        titleframe = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        titlename1 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t21 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        titlename = new javax.swing.JLabel();
        titlename2 = new javax.swing.JLabel();
        titlename3 = new javax.swing.JLabel();
        titlename4 = new javax.swing.JLabel();
        t5 = new javax.swing.JComboBox();
        t20 = new javax.swing.JComboBox();
        t14 = new javax.swing.JComboBox();
        t11 = new javax.swing.JComboBox();
        t10 = new javax.swing.JComboBox();
        t12 = new javax.swing.JComboBox();
        t19 = new javax.swing.JComboBox();
        t4 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(1365, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Name:");
        jLabel1.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 30));

        t1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 250, -1));

        t2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Father Name:");
        jLabel50.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 30));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Mother Name:");
        jLabel51.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 30));

        jLabel52.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Gender:");
        jLabel52.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 30));

        jLabel53.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Marital Status:");
        jLabel53.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 30));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Check in Date:");
        jLabel54.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 150, 30));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Check in Time:");
        jLabel55.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 20));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Family Docter Mob:");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 170, 30));

        jLabel59.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Problum Cateogry:");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 170, 30));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Patient Room Type:");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 170, 30));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Patient Room No:");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 170, 30));

        jLabel62.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Prefer Docter Name:");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 170, -1));

        jLabel63.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Patient Status:");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 392, 170, 30));

        jLabel65.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Phone no:");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 100, 30));

        jLabel66.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Email:");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, 100, 20));

        jLabel67.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Address:");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 100, -1));

        jLabel68.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Distric:");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 280, 100, -1));

        jLabel69.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("State:");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 320, 100, -1));

        jLabel70.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Country:");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 100, -1));

        jLabel71.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Pin code:");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 100, -1));

        titleframe.setBackground(new java.awt.Color(0, 153, 153));
        titleframe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        titleframe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital-building-clipart-vector_csp45854550.jpg"))); // NOI18N
        logo.setText("jLabel1");
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton10.setText("Logout");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        titlename1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename1.setForeground(new java.awt.Color(255, 255, 255));
        titlename1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename1.setText("HOSPITAL MANAGEMENT SYSTEM");
        titlename1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename1.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout titleframeLayout = new javax.swing.GroupLayout(titleframe);
        titleframe.setLayout(titleframeLayout);
        titleframeLayout.setHorizontalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(777, 777, 777)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleframeLayout.createSequentialGroup()
                    .addContainerGap(458, Short.MAX_VALUE)
                    .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(438, 438, 438)))
        );
        titleframeLayout.setVerticalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titleframeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleframeLayout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );

        getContentPane().add(titleframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        t6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 250, -1));

        t7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 250, -1));

        jTextField29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 250, -1));

        jTextField30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, -1));

        t3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, -1));

        t8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 250, -1));

        t9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 250, -1));

        t13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 250, -1));

        t15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, 250, -1));

        t16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 250, -1));

        t17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 250, -1));

        t18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 250, -1));

        t21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t21.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, 250, -1));

        jLabel73.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Family Docter Name:");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, 30));

        titlename.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename.setText("Contact Detail");
        titlename.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 110, 270, -1));

        titlename2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename2.setText("New Patient Registration");
        titlename2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename2.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 550, -1));

        titlename3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename3.setText("Basic Detail");
        titlename3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename3.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 270, -1));

        titlename4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename4.setText("Hospital Detail");
        titlename4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename4.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 270, -1));

        t5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", "Widowed", "Divorced", "Separated" }));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 250, 30));

        t20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "The Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica", "Côte d’Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Gabon", "The Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Japan", "Nepal", "Netherlands", "New Zealand", "Romania", "Russia", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "South Africa", "Spain", "Sri Lanka", "Sudan", "Sudan, South", "Suriname", "Sweden", "Switzerland", "Syria", "United Kingdom", "United States", "United Kingdom", "United States", " " }));
        getContentPane().add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 360, 250, 30));

        t14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Critical", "Critical but stable", "Serious", "Stable", "Satisfactory", "Comfortable", "Progressing well", "Normal", "Discharged", "Admit" }));
        getContentPane().add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 250, 30));

        t11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIP Suite", " Single Deluxe Room\t ", " Two-Bedded Room\t", " Four-Bedded Room\t", " Intensive Care Unit (ICU)\t", " Isolation Room\t ", " Labour & Delivery Suite\t", " Nursery\t" }));
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        getContentPane().add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 250, 30));

        t10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anaesthesiology & Critical Care", "Cardiology", "Cardiothoracic", "Ear, Nose & Throat (ENT), Head & Neck Surgery", "Emergency Medicine", "Gastroenterology & Hepatology", "General Surgery", "Gynaecologic Oncology", "Medical Oncology & Haematology ", "Neurology", "Neurosurgery", "Obstetrics & Gynaecology", "Ophthalmology", "Orthopaedic & Trauma Surgery", "Paediatrics & Neonatology", "Radiology & Interventional Radiology", "Respiratory & Internal Medicine", "Urology", "Skin Specialist", "Pediatric", "Dentist" }));
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 250, 30));

        t12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", " " }));
        getContentPane().add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 250, 30));

        t19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Andhra Pradesh ", "Arunachal Pradesh", "Assam ", "Bihar ", "Chhattisgarh", "Goa ", "Gujarat ", "Haryana ", "Himachal Pradesh ", "Jammu and Kashmir ", "Jharkhand ", "Karnataka ", "Kerala ", "Madhya Pradesh ", "Maharashtra ", "Manipur ", "Meghalaya ", "Mizoram ", "Nagaland ", "Odisha ", "Punjab ", "Rajasthan ", "Sikkim ", "Tamil Nadu ", "Telangana ", "Tripura ", "Uttar Pradesh ", "Uttarakhand ", "West Bengal " }));
        getContentPane().add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 320, 250, 30));

        t4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 43, 144, 33));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 43, 144, 33));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Close");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1098, 43, 144, 33));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1390, 130));

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("<html>\n<body>\n<footer >\n    <table>\n  <tr>\n    \n    <th  style=\"  color: white\">About us      <hr></th>\n     \n    <th style=\"color: white\">Address Info <hr></th>\n        \n    <th style=\"color: white\">Contact us\n          <hr>\n</th>\n  </tr>\n    \n  <tr>\n    <td rowspan=\"3\"  style=\"color: white\">Hospital management systeml, an initiative of <br> \"Health sectorl Plateform\", was founded with the idea of providing holistic value-based health that would help each patient to face lives challenges.</td> <td rowspan=\"2\"  style=\"color: white\">vivek hospital management system Kunda,<br> Locality: Pratapgarh (Reg.739)  state: uttarpradesh Landmark: 5kms sangramgarh polic station.</td>     <td rowspan=\"3\"  style=\"color: white\">Web site: www.healthmanagementsystem Phone: xxxxxxxxxx<br> Email:vivekpandey.nielit.gov.in For admisssions  Admissions Head Contact:- +91 xxxxxxxxx, +91 xxxxxxxxxx</td>   </tr>   </table>             <hr>     <h5 TEXT ALIGN=\"CENTER\"  style=\"color: white\"> Copyright @Hospital management system.</h5>    <hr>     </footer> </body> </html> ");
        jLabel5.setPreferredSize(new java.awt.Dimension(1436, 147));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1390, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        login a = null;
        try {
            a = new login();
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }

        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10MouseClicked

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       home regFace =new home();
     regFace.setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       t1.setText("");
t2.setText("");
t3.setText("");
t6.setText("");
t7.setText("");
t8.setText("");
t9.setText("");
t13.setText("");
t15.setText("");
t16.setText("");
t17.setText("");
t18.setText("");
t21.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     try {
                obj.thequery("insert into patient (`Name`, `Father`, `Mother`, `Gender`, `MaritalStatus`, `CheckinDate`, `CheckinTIme`, `FamilyDocter`, `FamilyDocterMob`, `ProblumCateog.`, `PatientRoom`, `Roomno.`, `PreferDoc`, `patientStatus`, `Phone`, `Email`, `Address`, `Distric`, `State`, `Country`, `PinCode`, `patient_reg`,  `Medicine_Name`, `Medicine_quantity`, `injection_Name`, `injection_quantity`, `testname`, `status`, `Appicationcharge`, `Doctercharge`, `Medicinecharge`, `Testcharge`, `Roomcharge`, `Extracharge`, `totalcharge`, `Statuspayment`) values('"+t1.getText()+"' , '"+t2.getText()+"' , '"+t3.getText()+"' , '"+t4.getSelectedItem().toString()+"' , '"+t5.getSelectedItem().toString()+"' , '"+t6.getText()+"' , '"+t7.getText()+"' , '"+t8.getText()+"' , '"+t9.getText()+"' , '"+t10.getSelectedItem().toString()+"' ,'"+t11.getSelectedItem().toString()+"' , '"+t12.getSelectedItem().toString()+"'  , '"+t13.getText()+"' , '"+t14.getSelectedItem().toString()+"' , '"+t15.getText()+"' , '"+t16.getText()+"' , '"+t17.getText()+"' , '"+t18.getText()+"' , '"+t19.getSelectedItem().toString()+"' , '"+t20.getSelectedItem().toString()+"' , '"+t21.getText()+"' , 'HP-"+numberAsString+"' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?' , '?')");
               
         String name = t1.getText();
            JOptionPane.showMessageDialog(null, " Mr."+name+" Welcome to hospital mang. your Account has been created..Your Registratio numberis: HP-"+numberAsString+"");
             home regFace =new home();
            regFace.setVisible(true);
                this.dispose();
        }catch(Exception ex){
          
        } 
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEWPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField t1;
    private javax.swing.JComboBox t10;
    private javax.swing.JComboBox t11;
    private javax.swing.JComboBox t12;
    private javax.swing.JTextField t13;
    private javax.swing.JComboBox t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JComboBox t19;
    private javax.swing.JTextField t2;
    private javax.swing.JComboBox t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t3;
    private javax.swing.JComboBox t4;
    private javax.swing.JComboBox t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JPanel titleframe;
    private javax.swing.JLabel titlename;
    private javax.swing.JLabel titlename1;
    private javax.swing.JLabel titlename2;
    private javax.swing.JLabel titlename3;
    private javax.swing.JLabel titlename4;
    // End of variables declaration//GEN-END:variables

    private static class Patient {

        public Patient() {
        }
    }
}
