
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OM SAI RAM
 */
public class payment extends javax.swing.JFrame {
sig obj = new sig();
Connection con=null;
    /**
     * Creates new form payment
     */
    public payment() throws SQLException {
         super("HOSPITAL MANAGEMENT SYSTEM");
        initComponents();
         con =DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L14 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        titlename3 = new javax.swing.JLabel();
        titlename2 = new javax.swing.JLabel();
        titleframe = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        titlename1 = new javax.swing.JLabel();
        L17 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        titlename23 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        titlename28 = new javax.swing.JLabel();
        titlename24 = new javax.swing.JLabel();
        titlename25 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        titlename26 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        titlename29 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        titlename30 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        titlename31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        id2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        L19 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        L21 = new javax.swing.JLabel();
        titlename34 = new javax.swing.JLabel();
        titlename35 = new javax.swing.JLabel();
        titlename36 = new javax.swing.JLabel();
        tuname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        titlename37 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        titlename32 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        titlename33 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L14.setText("State:");
        L14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 320, 20));

        L15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L15.setText("Country:");
        L15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 300, 20));

        L13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L13.setText("Distric:");
        L13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 320, -1));

        L12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L12.setText("Address:");
        L12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 300, -1));

        L11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L11.setText("Email:");
        L11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 170, -1));

        L9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L9.setText("Patient Status:");
        L9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 260, 20));

        L8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L8.setText("Prefer Docter Name:");
        L8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, -1));

        L7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L7.setText("Patient Room No:");
        L7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 250, 20));

        L6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L6.setText("Patient Room Type:");
        L6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 250, 20));

        L5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L5.setText("Problum Cateogry:");
        L5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, 20));

        L4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L4.setText("Check in Date:");
        L4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        L4.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 220, 20));

        L3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L3.setText("Marital Status:");
        L3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        L3.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 20));

        L2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2.setText("Gender:");
        L2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        L2.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 240, 20));

        L1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L1.setText("Patient Name:");
        L1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L1.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 250, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Name:");
        jLabel1.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 20));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Gender:");
        jLabel52.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 90, 20));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Marital Status:");
        jLabel53.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 20));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Check in Date:");
        jLabel54.setPreferredSize(new java.awt.Dimension(52, 22));
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 90, 20));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Problum Cateogry:");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, 20));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Patient Room Type:");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 150, 20));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Patient Room No:");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, 20));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Prefer Docter Name:");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 240, 150, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Patient Status:");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, 20));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Phone no:");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Email:");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 60, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Address:");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 60, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Distric:");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 60, -1));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("State:");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 360, 60, 20));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Country:");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, 80, 20));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        titlename3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titlename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename3.setText("Basic Detail");
        titlename3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename3.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 20));

        titlename2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename2.setText(" Patient Payment Dashboard :");
        titlename2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename2.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 550, 30));

        titleframe.setBackground(new java.awt.Color(0, 153, 153));
        titleframe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        titleframe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital-building-clipart-vector_csp45854550.jpg"))); // NOI18N
        logo.setText("jLabel1");
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton10.setText("Logout");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        titlename1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename1.setForeground(new java.awt.Color(255, 255, 255));
        titlename1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename1.setText("HOSPITAL MANAGEMENT SYSTEM");
        titlename1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename1.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout titleframeLayout = new javax.swing.GroupLayout(titleframe);
        titleframe.setLayout(titleframeLayout);
        titleframeLayout.setHorizontalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209)
                .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        titleframeLayout.setVerticalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(titleframeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(titleframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        L17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L17.setText("Email:");
        L17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        L10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L10.setText("Phone no:");
        L10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        L18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L18.setText("Phone no:");
        L18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 260, -1));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel71.setText("Pin code:");

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Reg_ no");

        L16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L16.setText("Pin code:");
        L16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        l19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l19.setText("Charge of Different section:");
        l19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        l19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        l19.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L16, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l19, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l19, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 390, 350));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        titlename23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename23.setText("Medicine charge:");
        titlename23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename23.setPreferredSize(new java.awt.Dimension(450, 28));

        t1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        t2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        t3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename28.setText("Application charge:");
        titlename28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename28.setPreferredSize(new java.awt.Dimension(450, 28));

        titlename24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename24.setText("Docter charge:");
        titlename24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename24.setPreferredSize(new java.awt.Dimension(450, 28));

        titlename25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename25.setText("Test charge:");
        titlename25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename25.setPreferredSize(new java.awt.Dimension(450, 28));

        t4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename26.setText("Room Charge :");
        titlename26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename26.setPreferredSize(new java.awt.Dimension(450, 28));

        t5.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename29.setText("Extra Charge :");
        titlename29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename29.setPreferredSize(new java.awt.Dimension(450, 28));

        t6.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename30.setText("Total Charge :");
        titlename30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename30.setPreferredSize(new java.awt.Dimension(450, 28));

        t7.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        titlename31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename31.setText("Charge of Different section:");
        titlename31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename31.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(titlename30, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(titlename29, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(t6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(titlename26, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(t5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(titlename24, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(t1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlename25, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlename23, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t3)
                            .addComponent(t4)))))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(titlename28, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(301, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(120, Short.MAX_VALUE)
                    .addComponent(titlename31, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlename24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlename23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlename30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(titlename28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(268, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(titlename31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(304, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 500, 350));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Payment");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269)
                .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1400, 310));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Pin code:");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 80, 10));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Pin code:");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 70, 20));

        L19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L19.setText("Pin code:");
        L19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 280, 20));

        L20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L20.setText("Pin code:");
        L20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 280, 20));

        L21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L21.setText("Pin code:");
        L21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(L21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 280, 20));

        titlename34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename34.setText("Check Payement Status:");
        titlename34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename34.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 310, -1));

        titlename35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename35.setText("Check Payement Status:");
        titlename35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename35.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 310, -1));

        titlename36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename36.setText("Enter Name/Email:");
        titlename36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename36.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename36, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 190, -1));

        tuname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tuname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(tuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 170, 270, 37));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Check Staus");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 250, 184, 38));

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));

        titlename37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename37.setText("Payement Status:");
        titlename37.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename37.setPreferredSize(new java.awt.Dimension(450, 28));

        a2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        a2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        a2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a2.setPreferredSize(new java.awt.Dimension(450, 28));

        titlename32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename32.setText("Total Amount Paid:");
        titlename32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename32.setPreferredSize(new java.awt.Dimension(450, 28));

        a1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        a1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        a1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1.setPreferredSize(new java.awt.Dimension(450, 28));

        titlename33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titlename33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename33.setText("Name:");
        titlename33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename33.setPreferredSize(new java.awt.Dimension(450, 28));

        a3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        a3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        a3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a3.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titlename37, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titlename32, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titlename33, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(a3, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlename33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlename32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlename37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 510, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        login a = null;
        try {
            a = new login();
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }

        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String a, b, c,d,e,f ;
        String data = "Succesfull";
        a = t1.getText();
        b=t2.getText();
        c=t3.getText();
         d=t4.getText();
          e=t5.getText();
           f=t6.getText();
         
   int sum = Integer.parseInt(a)+Integer.parseInt(b)+Integer.parseInt(c)+Integer.parseInt(d)+Integer.parseInt(e)+Integer.parseInt(f);
         String valu = String.valueOf(sum);
         Thread ab = new Thread();
         ab.start();
     t7.setText(valu);
        try {
        Thread.sleep(3);
    } catch (InterruptedException ex) {
        //Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
    }
        try {  obj.thequery("update patient set Appicationcharge ='"+t1.getText()+"' ,Doctercharge ='"+t2.getText()+"' ,Medicinecharge ='"+t3.getText()+"' ,Testcharge='"+t4.getText()+"',Roomcharge ='"+t5.getText()+"' ,Extracharge ='"+t6.getText()+"' ,totalcharge ='"+t7.getText()+"' ,Statuspayment ='Succesfull'   where patient_id ='"+id2.getText()+"'");       
           
JOptionPane.showMessageDialog(null, "Your Payement are processing please check the payement Status section.");
clear();

}
catch(Exception ex){
}
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       try{
            String query = "select * from patient";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            int c=0;
            String type = "User";
            while(rs.next()){
                                 int patient_id = rs.getInt(1);
                                String Name = rs.getString(2);
                                String Father = rs.getString(3);
                                String Mother = rs.getString(4);
				String Gender = rs.getString(5);
				String MaritalStatus = rs.getString(6);
				String CheckinDate = rs.getString(7);
				String CheckinTIme = rs.getString(8);
				String FamilyDocter = rs.getString(9);
				String FamilyDocterMob = rs.getString(10);
				String ProblumCateog = rs.getString(11);
				String PatientRoom = rs.getString(12);
				String 	Roomno = rs.getString(13);
				String PreferDoc = rs.getString(14);
				String 	patientStatus = rs.getString(15);
				String Phone = rs.getString(16);
				String 	Email = rs.getString(17);
				String Address = rs.getString(18);
				String 	Distric = rs.getString(19);
				String State = rs.getString(20);
				String 	Country = rs.getString(21);
				String PinCode = rs.getString(22);
				String patient_reg = rs.getString(23);
                                String medicinename = rs.getString(24);
                                 String quantity = rs.getString(25);
                                String injection = rs.getString(26);
                               String inquantity = rs.getString(27); 
                               String testname = rs.getString(28);
                               String status = rs.getString(29);
                                 String total = rs.getString(36);
                                 String payements = rs.getString(37);
                                 
                                             
                if(tuname.getText().equalsIgnoreCase(Email) || tuname.getText().equalsIgnoreCase(Name)){
                            
                  a1.setText(total);
                  a3.setText(Name);
                  a2.setText(payements);
                     
                           
                              
                       

                        
                        c=1;
                        break;
                  

                    
                }

            }
            if(c!=1)
            {
                JOptionPane.showMessageDialog(null,"your detail invalid sorry please try again !");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      
         home a = null;
         a = new home();

        a.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        clear();
    }//GEN-LAST:event_jButton4MouseClicked
void clear()
{
         t1.setText("");
       t2.setText("");
       t3.setText("");
       t4.setText("");
       t5.setText("");
       t6.setText("");
       t7.setText(""); 
       tuname.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new payment().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel L1;
    public javax.swing.JLabel L10;
    public javax.swing.JLabel L11;
    public javax.swing.JLabel L12;
    public javax.swing.JLabel L13;
    public javax.swing.JLabel L14;
    public javax.swing.JLabel L15;
    public javax.swing.JLabel L16;
    public javax.swing.JLabel L17;
    public javax.swing.JLabel L18;
    public javax.swing.JLabel L19;
    public javax.swing.JLabel L2;
    public javax.swing.JLabel L20;
    public javax.swing.JLabel L21;
    public javax.swing.JLabel L3;
    public javax.swing.JLabel L4;
    public javax.swing.JLabel L5;
    public javax.swing.JLabel L6;
    public javax.swing.JLabel L7;
    public javax.swing.JLabel L8;
    public javax.swing.JLabel L9;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    public javax.swing.JTextField id2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel l19;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JPanel titleframe;
    private javax.swing.JLabel titlename1;
    private javax.swing.JLabel titlename2;
    private javax.swing.JLabel titlename23;
    private javax.swing.JLabel titlename24;
    private javax.swing.JLabel titlename25;
    private javax.swing.JLabel titlename26;
    private javax.swing.JLabel titlename28;
    private javax.swing.JLabel titlename29;
    private javax.swing.JLabel titlename3;
    private javax.swing.JLabel titlename30;
    private javax.swing.JLabel titlename31;
    private javax.swing.JLabel titlename32;
    private javax.swing.JLabel titlename33;
    private javax.swing.JLabel titlename34;
    private javax.swing.JLabel titlename35;
    private javax.swing.JLabel titlename36;
    private javax.swing.JLabel titlename37;
    private javax.swing.JTextField tuname;
    // End of variables declaration//GEN-END:variables
}
